apiVersion: charts.k8s.f5net.com/v1alpha1
kind: SPKInstance
metadata:
  name: bnk-lab
  namespace: default
spec:
  tmstats:
    tmstatsConfig:
      resources:
        limits:
          cpu: 700m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
  controller:
    watchNamespace: red,blue
  cwc:
    persistence:
      enabled: true
      size: "5Gi"
    cpclConfig:
      jwt: $JWT
      operationMode: connected
  global:
    certmgr:
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: bnk-ca-cluster-issuer
    imagePullSecrets:
    - name: far-secret
    imageRepository: repo.f5.com/images
    logging:
      fluentbitSidecar:
        enabled: true
        fluentd:
          host: f5-toda-fluentd.f5-utils.svc.cluster.local
          port: "54321"
  spkInfrastructure: bnk-dpu-infra
  spkManifest: unused
  afm:
    enabled: true
    pccd:
      blob:
        maxFwBlobSizeMb: "512"
        maxNatBlobSizeMb: "512"
  tmm:
    replicaCount: 1
    nodeAssign:
      nodeSelector:
        app: f5-tmm
      tolerations:
        - key: "dpu"
          value: "true"
          operator: "Equal"
    palCPUSet: "2"
    usePhysMem: false
    resources:
      limits:
        cpu: ".1"
        memory: 2Gi
    debug:
      enabled: true
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 200m
          memory: 100Mi
    blobd:
      enabled: true
      resources:
        limits:
        requests:
          cpu: "0.1"
          memory: "1Gi"
    dynamicRouting:
      enabled: true
      configMapName: bnk-bgp
    tmrouted:
      resources:
        limits:
          cpu: "300m"
          memory: "512Mi"
        requests:
          cpu: "0.1"
          memory: "512Mi"
    tmmRouting:
      resources:
        limits:
          cpu: "700m"
          memory: "512Mi"
        requests:
          cpu: "0.1"
          memory: "512Mi"
    sessiondb:
      useExternalStorage: "true"
