apiVersion: k8s.f5.com/v1
kind: CNEInstance
metadata:
  labels:
    app.kubernetes.io/name: f5-lifecycle-operator
    app.kubernetes.io/managed-by: kustomize
  name: bnkgatewayclass-sample
spec:
  product:
    gatewayAPI: true
    type: BNK
  manifestVersion: "2.2.0-3.2226.0-0.0.385"
  wholeCluster: true
  telemetry:
    loggingSubsystem:
      enabled: false
    metricSubsystem:
      enabled: true
  certificate:
    clusterIssuer: bnk-ca-cluster-issuer
  deploymentSize: "Small"
  registry:
    uri: repo.f5.com
    imagePullSecrets:
    - name: far-secret
    imagePullPolicy: Always
  networkAttachments:
  - external-net
  - egress-net

  # Features
  # CSRC Egress
  pseudoCNI:
    enabled: true
  # BGP
  dynamicRouting:
    enabled: true
  # Core dump files
  coreCollection:
    enabled: false
  # AFM
  firewallACL:
    enabled: true

  advanced:
    demoMode:
      enabled: true
    maintenanceMode:
      enabled: false
    envDiscovery:
      enabled: false
      stopOnFail: true
      runAfterSuccess: true
    cneController:
      env:
      - name: "TMM_DEFAUlT_MTU"
        value: "1500"
    tmm:
      env:
      - name: "TMM_CALICO_ROUTER"
        value: "default"
      - name: "TMM_DEFAUlT_MTU"
        value: "1500"
      - name: "TMM_MAPRES_ADDL_VETHS_ON_DP"
        value: "TRUE"
      - name: "ZEBOS_STATE"
        value: legacy
    #  - name: "TMM_LOG_LEVEL"
    #    value: "Debug"
    pseudoCNI:
      env:
      - name: "EXCLUDE_CIDR"
        value: "10.96.0.0/12,10.244.0.0/16,198.168.20.0/24,10.11.0.0/16"
