kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bnk
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      # Grafana access.
      - containerPort: 32000
        hostPort: 3000
      # Prometheus access.
      - containerPort: 30000
        hostPort: 8080
  - role: worker
  - role: worker
  - role: worker
networking:
  ipFamily: dual
  disableDefaultCNI: true
