---
apiVersion: "k8s.f5net.com/v1"
kind: F5SPKVlan
metadata:
  name: external
spec:
  name: external
  interfaces:
    - "1.1"
  selfip_v4s:
    - 192.0.2.201
    - 192.0.2.202
  prefixlen_v4: 24
  selfip_v6s:
    - 2001::192:0:2:201
    - 2001::192:0:2:202
  prefixlen_v6: 112
  auto_lasthop: "AUTO_LASTHOP_ENABLED"
---
apiVersion: "k8s.f5net.com/v1"
kind: F5SPKVlan
metadata:
  name: egress
spec:
  name: egress
  interfaces:
    - "1.2"
  selfip_v4s:
    - 198.18.100.201
    - 198.18.100.202
  prefixlen_v4: 24
  selfip_v6s:
    - 2001::198:18:100:201
    - 2001::198:18:100:202
  prefixlen_v6: 112
  auto_lasthop: "AUTO_LASTHOP_ENABLED"
