!
! Zebra configuration saved from vty
!   2025/02/06 01:41:58
!
frr version 8.4.6_git
frr defaults traditional
!
hostname router
log file /tmp/frr.log
!
debug bgp neighbor-events
debug bgp update-groups
debug bgp updates in
debug bgp updates out
debug bgp zebra
debug bgp graceful-restart
!
!
!
router bgp 65500
 bgp router-id 192.0.2.250
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor SPK-PODS peer-group
 neighbor SPK-PODS remote-as external
 bgp listen range 192.0.2.0/24 peer-group SPK-PODS
 bgp listen range 2001::192:0:2:0/112 peer-group SPK-PODS
 !
 address-family ipv4 unicast
  network 198.51.100.0/24
  neighbor SPK-PODS activate
  neighbor SPK-PODS soft-reconfiguration inbound
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor SPK-PODS activate
  neighbor SPK-PODS soft-reconfiguration inbound
 exit-address-family
!
exit
!
!
!
!
!
